package example;


/**
* example/fibonacciOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from fibonacci.idl
* martes 12 de junio de 2018 11:46:08 AM CDT
*/

public interface fibonacciOperations 
{

  /*
           * Para generar 
           * in: el valor del parametro se lo envia el cliente al servidor
           * long: -231..231-1 (32 bits)
           * numero: nombre de la variable
          */
  String generar (int numero);
} // interface fibonacciOperations
