package example;


/**
* example/fibonacci.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from fibonacci.idl
* martes 12 de junio de 2018 11:46:08 AM CDT
*/

public interface fibonacci extends fibonacciOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface fibonacci
